package com.bigbang.sorting;

/*
 * @ Created with IntelliJ IDEA
 * @ Author Bang Peng
 * @ Version 1.0.0
 * @ Since 1.0.0
 * @ Date 2021/8/28
 * @ Time 13:06
 */
public class LeetCode389FindTheDifference {
    /**
     * You are given two strings s and t.
     * <p>
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * <p>
     * Return the letter that was added to t.
     * <p>
     * <p>
     * <p>
     * Example 1:
     * <p>
     * Input: s = "abcd", t = "abcde"
     * Output: "e"
     * Explanation: 'e' is the letter that was added.
     * Example 2:
     * <p>
     * Input: s = "", t = "y"
     * Output: "y"
     * Example 3:
     * <p>
     * Input: s = "a", t = "aa"
     * Output: "a"
     * Example 4:
     * <p>
     * Input: s = "ae", t = "aea"
     * Output: "a"
     * <p>
     * <p>
     * Constraints:
     * <p>
     * 0 <= s.length <= 1000
     * t.length == s.length + 1
     * s and t consist of lower-case English letters.
     *
     * @param s
     * @param t
     * @return
     */
    public static char findTheDifference(String s, String t) {
        //Runtime: 1 ms, faster than 98.56% of Java online submissions for Find the Difference.
        //Memory Usage: 39.1 MB, less than 10.85% of Java online submissions for Find the Difference.
        
        int[] temp = new int[26];
        for (char c : s.toCharArray())
            temp[c - 'a']++;
        for (char c : t.toCharArray())
            temp[c - 'a']--;
        for (int i = 0; i < temp.length; i++) {
            if (temp[i] < 0)
                return (char) (i + 97);
        }
        return t.toCharArray()[0];
    }

    public static void main(String[] args) {
        String s = "", t = "a";
        System.out.println(findTheDifference(s, t));
    }
}
